### ISSUE TITLE
while Build SoftISP Demoapp I am getting this errors

### ISSUE THREAD

**Issue by paragikjain** [NXPmicro/gtec-demo-framework#1]
While Building SoftISP DemoApplication for android I am getting this warning and not able to build

<pre>WARNING: Recipe.BuildTool.ninja was marked as not supported on this platform by package: ['Recipe.BuildTool.ninja_1_8_2']
WARNING: OpenCL.SoftISP was marked as not supported on this platform by package: ['OpenCL', 'OpenCL.SoftISP']
WARNING: Recipe.BuildTool.ninja_1_8_2 was marked as not supported on this platform by package: ['Recipe.BuildTool.ninja_1_8_2']
WARNING: FslUtil.OpenCL1_2 was marked as not supported on this platform by package: ['OpenCL']
WARNING: FslDemoApp.OpenCL was marked as not supported on this platform by package: ['OpenCL']
WARNING: RapidOpenCL1 was marked as not supported on this platform by package: ['OpenCL']
WARNING: OpenCL1_2 was marked as not supported on this platform by package: ['OpenCL']
WARNING: OpenCL was marked as not supported on this platform by package: ['OpenCL']
WARNING: FslUtil.OpenCL was marked as not supported on this platform by package: ['OpenCL']
WARNING: Recipe.RapidOpenCL_1_1_0_1 was marked as not supported on this platform by package: ['OpenCL']
No executables left, skipping all</pre>

**Comment by ReneThrane** [comment]
Yes we do not support compiling that application for android.

As mentioned by the warnings the packages: OpenCL and OpenCL.SoftISP
Are not supported when building for Android, so there is nothing to compile.

One of the reasons for this is that OpenCL is not provided with the standard android SDK and we do not currently provide any recipe for how it should be build it for android.
